-- Migration: Add workflow columns to conversation_tasks table
-- This migration adds the missing workflow-related columns that were defined in schema but not in database

ALTER TABLE conversation_tasks 
ADD COLUMN IF NOT EXISTS workflow_task_id UUID REFERENCES workflow_tasks(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS is_workflow_generated BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS workflow_metadata JSONB DEFAULT '{}';

-- Create index for workflow-related tasks
CREATE INDEX IF NOT EXISTS idx_conversation_tasks_workflow 
ON conversation_tasks(workflow_task_id) 
WHERE workflow_task_id IS NOT NULL;

-- Add comment
COMMENT ON COLUMN conversation_tasks.workflow_task_id IS 'Reference to the workflow task that generated this conversation task';
COMMENT ON COLUMN conversation_tasks.is_workflow_generated IS 'Indicates if this task was automatically generated by a workflow';
COMMENT ON COLUMN conversation_tasks.workflow_metadata IS 'Additional metadata about the workflow that generated this task';