/**
 * Matches the XXXX-XXXX user code format generated by the device auth flow.
 * Uses the unambiguous alphabet: A-Z (no O/I/L) + 2-9 (no 0/1).
 *
 * Shared between server validation (_shared.ts) and client pre-check (page.tsx).
 */
export const USER_CODE_PATTERN = /^[A-Z2-9]{4}-[A-Z2-9]{4}$/;
