/**
 * The unambiguous alphabet used by userCodeGen in initiate/route.ts.
 * Excludes 0/O, 1/I/L to prevent transcription errors.
 */
export const USER_CODE_ALPHABET = 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';

/**
 * Matches the XXXX-XXXX user code format generated by the device auth flow.
 * Character class mirrors USER_CODE_ALPHABET exactly.
 *
 * Shared between server validation (_shared.ts) and client pre-check (page.tsx).
 */
export const USER_CODE_PATTERN = /^[ABCDEFGHJKMNPQRSTUVWXYZ23456789]{4}-[ABCDEFGHJKMNPQRSTUVWXYZ23456789]{4}$/;
