import { desc, eq } from 'drizzle-orm';
import { getServerSession } from 'next-auth/next';
import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';

import { db } from '@/db';
import { deviceAuthCodesTable } from '@/db/schema';
import { createErrorResponse, ErrorResponses } from '@/lib/api-errors';
import { authOptions } from '@/lib/auth';
import { createRateLimiter } from '@/lib/rate-limiter';

export const authActionRateLimiter = createRateLimiter({
  windowMs: 5 * 60 * 1000,
  max: 10,
});

// Matches the XXXX-XXXX format generated by initiate (unambiguous alphabet)
const userCodeSchema = z.object({
  user_code: z.string().regex(/^[A-Z2-9]{4}-[A-Z2-9]{4}$/),
});

type DeviceAuthRecord = typeof deviceAuthCodesTable.$inferSelect;

type ValidatedRequest =
  | { ok: true; record: DeviceAuthRecord; session: { user: { id: string } }; userCode: string; body: Record<string, unknown> }
  | { ok: false; response: NextResponse };

/**
 * Shared validation for approve/deny endpoints:
 * - Rate limiting
 * - Session authentication
 * - JSON body parsing + Zod validation
 * - Device auth code lookup by user_code (most recent match)
 * - Status check (must be 'pending')
 * - Expiration check (auto-expires stale codes)
 *
 * Note: No CSRF token needed — the user_code (visible only in the user's
 * terminal and on this authenticated page) acts as an implicit CSRF token.
 *
 * Returns the full parsed body so callers can extract additional fields.
 */
export async function validateDeviceAuthAction(
  request: NextRequest,
): Promise<ValidatedRequest> {
  const rateLimitResult = await authActionRateLimiter(request);
  if (!rateLimitResult.allowed) {
    return {
      ok: false,
      response: NextResponse.json(
        { error: 'Too many requests', code: 'RATE_LIMIT_EXCEEDED' },
        { status: 429 }
      ),
    };
  }

  const session = await getServerSession(authOptions);
  if (!session?.user?.id) {
    return { ok: false, response: ErrorResponses.unauthorized() };
  }

  let body: Record<string, unknown>;
  try {
    body = await request.json();
  } catch {
    return { ok: false, response: ErrorResponses.badRequest('Invalid JSON body') };
  }

  const validated = userCodeSchema.safeParse(body);
  if (!validated.success) {
    return { ok: false, response: ErrorResponses.badRequest('Invalid request parameters') };
  }

  const { user_code } = validated.data;

  // Single query — fetch the most recent record for this user_code,
  // then branch on status/expiry in application code
  const record = await db.query.deviceAuthCodesTable.findFirst({
    where: eq(deviceAuthCodesTable.user_code, user_code),
    orderBy: desc(deviceAuthCodesTable.created_at),
  });

  if (!record) {
    return { ok: false, response: ErrorResponses.notFound() };
  }

  if (record.status === 'expired') {
    return {
      ok: false,
      response: createErrorResponse('Authorization code expired', 410, 'EXPIRED'),
    };
  }

  if (record.status !== 'pending') {
    return {
      ok: false,
      response: createErrorResponse('Authorization code already used', 409, 'ALREADY_USED'),
    };
  }

  if (new Date() > record.expires_at) {
    await db.update(deviceAuthCodesTable)
      .set({ status: 'expired' })
      .where(eq(deviceAuthCodesTable.uuid, record.uuid));
    return {
      ok: false,
      response: createErrorResponse('Authorization code expired', 410, 'EXPIRED'),
    };
  }

  return {
    ok: true,
    record,
    session: session as { user: { id: string } },
    userCode: user_code,
    body,
  };
}
